### PR TITLE
Support custom dataset

### PR DESCRIPTION
**Pull request by zlapp**
Hi,

I wanted to test out simclr and supcontrast on custom datasets and see how they perform.
In the PR I made minimal changes to support passing in a path to the dataset, mean, and std to initialize a PyTorch ImageFolder dataset.

Thanks
@zlapp

### CODE REVIEW

**Comment by HobbitLong** [comment]
Thanks @zlapp very much for your contribution.

One question before merging it, do you assume images in the dataset also to be resized to 32?

**Comment by zlapp** [comment]
My pleasure @HobbitLong. 
Was debating what the correct approach is.
Do you think that the correct approach is to make the resize dim configurable here?: 
https://github.com/zlapp/SupContrast/blob/5406a1cc8a41dc5d7cf5e9332d794b18a300836e/main_supcon.py#L146

**Comment by zlapp** [comment]
Added size as an argument with default of 32

**Comment by HobbitLong** [comment]
LGTM, thank you very much! Merged

**Pull request merged**
